In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score
from sklearn.preprocessing import StandardScaler


In [2]:
df = pd.read_excel("Titanic.xlsx")
print(df.head())


   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [3]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
data = df[[ 'Pclass', 'Sex', 'Age', 'Fare','Survived']]

In [9]:
data = data.dropna()

In [10]:
X=data[[ 'Pclass', 'Sex', 'Age', 'Fare']]

In [11]:
X

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
885       3  female  39.0  29.1250
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[714 rows x 4 columns]

In [12]:
y = data['Survived']

In [13]:
# Sex: male=0, female=1
X["Sex"] = X["Sex"].map({"male": 0, "female": 1})


C:\Users\hp\AppData\Local\Temp\ipykernel_1112\1271114200.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Sex"] = X["Sex"].map({"male": 0, "female": 1})


In [14]:
X

Pclass  Sex   Age     Fare
0         3    0  22.0   7.2500
1         1    1  38.0  71.2833
2         3    1  26.0   7.9250
3         1    1  35.0  53.1000
4         3    0  35.0   8.0500
..      ...  ...   ...      ...
885       3    1  39.0  29.1250
886       2    0  27.0  13.0000
887       1    1  19.0  30.0000
889       1    0  26.0  30.0000
890       3    0  32.0   7.7500

[714 rows x 4 columns]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)


In [16]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [17]:
X_train_scaled

array([[ 9.28167783e-01,  1.32606716e+00,  6.68025202e-02,
        -2.93819129e-01],
       [ 9.28167783e-01, -7.54109620e-01, -2.72964097e-01,
        -4.16381382e-01],
       [ 9.28167783e-01, -7.54109620e-01, -1.15080322e-03,
        -3.83154632e-01],
       ...,
       [-1.45914665e+00,  1.32606716e+00,  7.46335754e-01,
         2.00720098e+00],
       [ 9.28167783e-01, -7.54109620e-01,  2.02709167e-01,
        -2.93819129e-01],
       [ 9.28167783e-01, -7.54109620e-01,  2.02709167e-01,
        -5.48787702e-01]], shape=(571, 4))

In [18]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train_scaled, y_train)


LogisticRegression(max_iter=1000)

In [19]:
y_pred = model.predict(X_test_scaled)
y_proba = model.predict_proba(X_test_scaled)[:, 1]


In [20]:
y_pred

array([0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [21]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)


Accuracy: 0.7412587412587412


In [22]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)


Confusion Matrix:
 [[68 19]
 [18 38]]


In [23]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.79      0.78      0.79        87
           1       0.67      0.68      0.67        56

    accuracy                           0.74       143
   macro avg       0.73      0.73      0.73       143
weighted avg       0.74      0.74      0.74       143



In [24]:
roc_auc = roc_auc_score(y_test, y_proba)
print("ROC-AUC:", roc_auc)


ROC-AUC: 0.8111658456486042


In [ ]:
Pclass	Sex	Age	Fare

In [25]:
a = scaler.transform([[2,0,59,10]])

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [26]:
model.predict(a)

array([0])

In [27]:
b = scaler.transform([[1,1,25,80]])

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [28]:
model.predict(b)

array([1])

In [29]:
model.predict_proba(b)

array([[0.04986366, 0.95013634]])

In [30]:
model.predict_proba(a)

array([[0.91697825, 0.08302175]])